### DISCUSSION TITLE
Add x 40lbs bag os salt in MQTT

### DISCUSSION THREAD

**Discussion by psmith3** [tagyoureit/nodejs-poolController#477] [App and O/S Config Questions] [answered]
I noticed tonight that the controller is telling me to add 2.32 40lbs bags of salt to my pool based on the salt level. My Pool is 27,835 gallons defined in the body and my salt is at 3000 PPM. I like to keep it around 3200-3300  PPM. Also, is this value available in the MQTT feed? I would like to see this in Home Assistant. 
<img width="253" alt="image" src="https://user-images.githubusercontent.com/14373163/172531583-71b0983b-6372-406d-8089-e72fc643c44e.png">

**Comment by rstrouse** [comment, marked as answer]
Yes this is based on the ideal salt level of 3400ppm.  Bear in mind that the chlorinator reporting can be off +- 500ppm as yes even the salt test kits with reagent can be off the same amount.  A good rule of thumb is to take care to not add more than half the recommended salt from either testing method until the water temperature sustains 80F for 48 hours.

If you pull njsPC the saltRequired values have been added to the MQTT events.

**Comment by psmith3** [comment]
Awesome! I can see the saltRequired in the MQTT now! I assume the 3400PPM number is hardcoded in the config?

Thanks very much!

**Reply by rstrouse** [reply]
Yes 3400 is hardcoded.  Maybe at some point we will add a target value.

**Comment by psmith3** [comment]
No worries! This is what I did with the new MQTT value! The Add Salt markdown / filter card only shows up if the add salt value is greater than 0.

![Dashboard](https://user-images.githubusercontent.com/14373163/173902499-4164fe1f-0f8c-4e1d-bcd8-605419ef425d.png)

In case anyone wants to recreate this Lovelace dashboard, here is my yaml code.

```
type: vertical-stack
cards:
  - type: gauge
    entity: sensor.pool_salt_level
    min: 2000
    max: 4000
    severity:
      green: 2700
      yellow: 3400
      red: 1
    needle: true
  - type: entity-filter
    entities:
      - sensor.salt_required
    state_filter:
      - operator: '>'
        value: 40
    card:
      type: markdown
      content: >-
        <ha-alert title="ADD SALT">Add **{{ ( states('sensor.salt_required') |
        int / 40 ) | round(1) }}**, 40 lb bags of Salt **({{ (
        states('sensor.salt_required')) }} lbs.)**</ha-alert>
  - type: gauge
    entity: sensor.pool_chlorinator_current_output
    min: 0
    max: 100
    needle: true
    segments:
      - from: 0
        color: '#db4437'
      - from: 5
        color: '#009dff'
      - from: 95
        color: '#ffa600'
  - type: entities
    entities:
      - entity: sensor.pool_chlorinator_status
      - entity: switch.pool_chlorinator
      - entity: input_number.pool_chlorine_set_point
      - entity: sensor.super_chlorinate_hours
      - entity: input_number.pool_superchlor_set_hours
      - entity: switch.super_chlorinate
      - entity: sensor.salt_required
    show_header_toggle: false
    state_color: true
    title: AquaRite 940 Salt Chlorinator
```

configuration.yaml here:

```
sensor:
- platform: mqtt
name: 'Pool Salt Level'
unique_id: sensor.pool_salt_level
icon: mdi:shaker-outline
state_topic: "nixie-singlebody/state/chlorinators/1/aquarite/saltLevel"
value_template: "{{ value_json.saltLevel }}"
unit_of_measurement: ppm
- platform: mqtt
name: "Pool Chlorinator Status"
unique_id: sensor.pool_chlorinator_status
icon: mdi:check-circle-outline
state_topic: "nixie-singlebody/state/chlorinators/1/aquarite/status"
value_template: "{{ value_json.status.desc }}"

- platform: mqtt
name: "Pool Chlorinator Current Output"
unique_id: sensor.pool_chlorinator_current_output
icon: mdi:chemical-weapon
state_topic: "nixie-singlebody/state/chlorinators/1/aquarite/currentOutput"
value_template: "{{ value_json.currentOutput | round(1) }}"
unit_of_measurement: '%'

- platform: mqtt
name: "Super Chlorinate"
unique_id: sensor.pool_superClorinator_status
icon: mdi:lightbulb
state_topic: "nixie-singlebody/state/chlorinators/1/aquarite/superChlor"
value_template: "{{ value_json.superChlor }}"

- platform: mqtt
name: "Super Chlorinate Hours"
unique_id: sensor.super_clorinate_hours
icon: mdi:clock
state_topic: "nixie-singlebody/state/chlorinators/1/aquarite/superChlorHours"
value_template: "{{ value_json.superChlorHours }}"

- platform: mqtt
name: 'Salt Required'
unique_id: sensor.pool_salt_required
icon: mdi:shaker-outline
state_topic: "nixie-singlebody/state/chlorinators/1/aquarite/saltRequired"
value_template: "{{ value_json.saltRequired }}"
unit_of_measurement: lbs

switch:

#Pool Controller Sensors
- platform: mqtt
name: "Pool Chlorinator"
unique_id: switch.pool-chlorinator
icon: mdi:pool
state_topic: "nixie-singlebody/state/circuits/6/pool"
value_template: "{{ value_json.isOn }}"
command_topic: "nixie-singlebody/state/circuits/toggleState"
payload_on: '{"id": 6}'
payload_off: '{"id": 6}'
state_on: "on"
state_off: "off"
optimistic: false
retain: false
qos: 0

- platform: mqtt
name: "Super Chlorinate"
unique_id: switch.pool-superChlorinate
icon: mdi:light-switch
state_topic: "nixie-singlebody/state/chlorinators/1/aquarite/superChlor"
value_template: "{{ value_json.superChlor }}"
command_topic: "nixie-singlebody/state/chlorinator"
payload_on: '{"id":1,"superChlor":"on"}'
payload_off: '{"id":1,"superChlor":"off"}'
state_on: "on"
state_off: "off"
optimistic: false
retain: false
qos: 0

input_number:
pool_chlorine_set_point:
name: Pool Chlorine Set Point
min: 0
max: 100
step: 10
icon: mdi:target
unit_of_measurement: "%"

pool_superchlor_set_hours:
name: Set Super Chlorinate Hours
min: 1
max: 24
#step: 1
icon: mdi:clock
unit_of_measurement: "Hours"
```

automations.yaml here:

```
- id: '808456'
alias: Set SWG slider
trigger:
- platform: mqtt
topic: nixie-singlebody/state/chlorinators/1/aquarite/poolSetpoint
action:
- service: input_number.set_value
target:
entity_id: input_number.pool_chlorine_set_point
data:
value: '{{ trigger.payload_json.poolSetpoint }}'

- id: '1652815248891'
alias: SWG slider moved
description: ''
trigger:
- platform: state
entity_id:
- input_number.pool_chlorine_set_point
condition: []
action:
- service: mqtt.publish
data:
topic: nixie-singlebody/state/chlorinator
retain: true
payload: '{"id":1,"poolSetpoint":{{ states(''input_number.pool_chlorine_set_point'')|round(0)}}}'
mode: single

- id: '1652830228832'
alias: Set Pool Chlorinator Hours slider
description: ''
trigger:
- platform: mqtt
topic: nixie-singlebody/state/chlorinators/1/aquarite/superChlorHours
condition: []
action:
- service: input_number.set_value
target:
entity_id: input_number.pool_superchlor_set_hours
data:
value: '{{ trigger.payload_json.superChlorHours | round(0) }}'
mode: single

- id: '1652831179931'
alias: Pool Chlorinator Hours slider moved
description: ''
trigger:
- platform: state
entity_id:
- input_number.pool_superchlor_set_hours
condition: []
action:
- service: mqtt.publish
data:
topic: nixie-singlebody/state/chlorinator
retain: true
payload: '{"id":1,"superChlorHours":{{ states(''input_number.pool_superchlor_set_hours'')|round(0)}}}'
mode: single
```

I just saw in your other message that the “- platform: mqtt" is going to change with HASS. Will update at that point.
