### DISCUSSION TITLE
Excessive disk activity?

### DISCUSSION THREAD

**Discussion by MaxVonEvil** [tagyoureit/nodejs-poolController#909] [App and O/S Config Questions] [answered]
Hi all, not sure if this is a bug or something which can be resolved by tweaking the configuration of NJSPC. However I am experiencing non-stop disk activity when NJSPC is running.

I've been running it for a long time on a Pi, but since the SD card crashed last year I moved NJSPC to run as a docker container on my Synology 920+ NAS, using their Container Manager + an EW-11 network RS485 server. **Everything works nicely.**

However I've noticed my disks in my NAS are churning non-stop when I have the poolcontroller container running. I've verified that I have no logging options enabled as well as I have zero of the advanced features (heaters, chems, lights, rem, etc.) enabled. I basically just use NJSPC for controlling the speed of my IntelliFlo-VS pump and reading the watts, that's really all. I can post copies of my config.json files, but there's not that much interesting in them.

My docker file looks like this: 

```
services:
  poolcontroller:
    container_name: poolcontroller
    restart: always
    user: node:dialout
    ports:
      - "4200:4200"
    volumes:
    - /volume1/docker/njspc/poolcontroller/data:/app/data
    - type: bind
      source: /volume1/docker/njspc/poolcontroller/config.json
      target: /app/config.json
    image: msmi/nodejs-poolcontroller
  poolcontroller-dashpanel:
    restart: always
    container_name: poolcontroller-dashpanel
    ports:
      - "5150:5150"
    volumes:
    - type: bind
      source: /volume1/docker/njspc/poolcontroller-dashpanel/config.json
      target: /app/config.json
    image: msmi/nodejs-poolcontroller-dashpanel
    depends_on:
      - poolcontroller
```

My thought is that if no logging is enabled, why would it need to have this much if any disk activity, once loaded up, it should just be all comms and ram, right?

Any suggestions are welcome!
