### ISSUE TITLE
Add Home Assistant Setup Instructions to Wiki

### ISSUE THREAD

**Issue by sonapsent** [tagyoureit/nodejs-poolController#330]
As requested here is a writeup for the wiki to setup with Home Assistant. I am new to this, so look it over and let me know if you would like to see any changes.

[nodePC - HA.md](https://github.com/tagyoureit/nodejs-poolController/files/6835416/nodePC.-.HA.md)

**Comment by truvec** [comment]
Looks good. Your post inspired me set this up too. Here are two automations that could be used instead of NodeRed to keep the input selects in sync.

```
automation:
  - id: '808456'
    alias: "Set SWG slider"
    trigger:
      platform: mqtt
      topic: "pool/state/chlorinators/1/aquarite/poolSetpoint"
    action:
      service: input_number.set_value
      target:
        entity_id: input_number.pool_chlorine_set_point
      data:
        value: "{{ trigger.payload_json.poolSetpoint }}"

  - id: '808457'
    alias: "SWG slider moved"
    trigger:
      platform: state
      entity_id: input_number.pool_chlorine_set_point
    action:
      service: mqtt.publish
      data:
        topic: "pool/state/chlorinator"
        retain: true
        payload: "{\"id\":1,\"poolSetpoint\":{{ states('input_number.pool_chlorine_set_point')|round(0)}}}"
```
