### ISSUE TITLE
[BUG] Changing the speed of a pump deletes the pump

### ISSUE THREAD

**Issue by terafin** [tagyoureit/nodejs-poolController#451]
### nodejs-poolController Version/commit

9d224de

### nodejs-poolController-dashPanel Version/commit

d932f2f

### Node Version

docker

### Platform

docker

### Are you using Docker?

- [X] Yes.

### OCP

EasyTouch 2 4P

### Pump(s)

Intelliflo VS

### What steps will reproduce the bug?

Click on the pump here:
<img width="391" alt="Screen Shot 2022-05-19 at 2 22 07 PM" src="https://user-images.githubusercontent.com/66893/169407141-4e1c6031-a873-48c9-9bcc-af05ac33183c.png">
 
Change the speed (RPM) of the pump

Wait a few moments, and this shows up:
<img width="397" alt="Screen Shot 2022-05-19 at 1 43 08 PM" src="https://user-images.githubusercontent.com/66893/169407187-e830567f-ff6a-4300-a409-22088c817a3c.png">

### What happens?

• Pump turns off
• If I go to the panel, the circuit is removed from the pump

### What should have happened?

RPM changed :)

### Additional information

[replay (2).zip](https://github.com/tagyoureit/nodejs-poolController/files/8734326/replay.2.zip)

**Comment by rstrouse** [comment]
Please pull njsPC and make sure your dashPanel is up to date as well.  I cleaned up the code a little bit but I am surprised at our outgoing message.  It is indicating that the circuit should be deleted.

**Comment by terafin** [comment]
Updating them now... thanks!

**Comment by terafin** [comment]
Still seemed to fail, will upload new logs in a few minutes, as I need to add it back at the panel

**Comment by terafin** [comment]
Adding logs from this happening again

**Comment by terafin** [comment]
[replay 3.zip](https://github.com/tagyoureit/nodejs-poolController/files/8734787/replay.3.zip)

**Comment by terafin** [comment]
<img width="405" alt="Screen Shot 2022-05-19 at 4 41 35 PM" src="https://user-images.githubusercontent.com/66893/169422246-9f0e44b2-485e-451d-9d99-a35ffe7bb8cc.png">
Here's the full system config

**Comment by vj950** [comment]
I can confirm that on my Intellitouch i93+3s system, this issue is fixed.

**Comment by rstrouse** [comment]
I have set my system up to emulate yours.  This is very odd your call to change the speed from the browser looks like the following
``` 
   PUT /config/pump 
   {"id":1,
    "circuits":[
           {"speed":1900,"units":{"val":0},"id":1,"circuit":6},
           {"speed":2100,"units":{"val":0},"id":2,"circuit":6}
      ]
   }
```

And the correct call which is what I am seeing is as follows.
```
   PUT /config/pump 
   {"id":1,
    "circuits":[
         {"speed":2150,"units":{"val":0},"id":1,"circuit":6}
     ]
}
```

Your request is insisting on setting two different values for the same pool circuit (6).  That will cause a definite choke.  The only way this can be is if your dashPanel is not up to date.  Please hard refresh your browser.  Perhaps you have some cached script or the docker container did not recompile the script before running it.  I have never used docker so I don't know what it does with cached files.

When you bring up the screen to change the speeds I assume it looks like this.
![image](https://user-images.githubusercontent.com/47839015/169434905-30611d7f-989f-44a8-940c-7868c5d3168e.png)

**Comment by terafin** [comment]
<img width="798" alt="Screen Shot 2022-05-19 at 7 17 38 PM" src="https://user-images.githubusercontent.com/66893/169435492-903d83b0-eccc-4b4f-b9a4-2bc7e70f29c9.png">

I can confirm that this is my same setup. 

Just ran this in private browsing mode, and had the same results after changing it...

<img width="822" alt="Screen Shot 2022-05-19 at 7 18 55 PM" src="https://user-images.githubusercontent.com/66893/169435596-b3e1e446-fc06-4304-813d-da695027fe6b.png">
 
Will try a clean docker container (with no mounts).

Note I'm using msmi's docker setup. :) 

Trying a few permutations now...

**Comment by terafin** [comment]
@rstrouse I can also provide remote access for this FYI, if this is useful debugging to take out the middle man :)

**Comment by terafin** [comment]
Notes:
```
Log
7:40 PM kicked off fresh docker containers with no storage
7:42 PM connected fresh dash panel to controller
7:43 PM started packet capture (with config reload)
7:43 PM config reload complete
7:44 PM toggled pump off then on from web ui
** aside note heater status reported “Heatpump” but “Heat mode” is off
7:46 PM (after priming settled) used UI to change the RPM from 2100 to 2200
7:46 PM pump shut off
7:47 PM using web UI, re-added pump on “Pool” circuit, and saved it
7:47 PM toggled pump off and on from web ui
7:48-49 PM went to easy touch panel, and selected pump, re-attached to circuit “Pool”, set RPM to 2100
Worked

```
Logs:
[replay (3).zip](https://github.com/tagyoureit/nodejs-poolController/files/8735413/replay.3.zip)

Docker setup:
```
  poolcontroller:
    logging: *default-logging
    container_name: poolcontroller
    restart: always
    user: node:dialout
    devices:
      - /dev/ttyUSB0
    environment:
      TZ: America/Los_Angeles
      PUID: 1000
      PGID: 1000
    ports:
      - "4200:4200"
    image: msmi/nodejs-poolcontroller:latest
  poolcontroller-dashpanel:
    restart: always
    logging: *default-logging
    container_name: poolcontroller-dashpanel
    ports:
      - "5150:5150"
    image: msmi/nodejs-poolcontroller-dashpanel
    environment:
      TZ: America/Los_Angeles
      PUID: 1000
      PGID: 1000
    depends_on:
      - poolcontroller
````

System con
<img width="422" alt="Screen Shot 2022-05-19 at 7 50 46 PM" src="https://user-images.githubusercontent.com/66893/169439221-9cff51b3-3614-4de9-8d96-f822604d1aeb.png">
fig:
