### ISSUE TITLE
[BUG] Docker images post 7.6.1 fail to start for me

### ISSUE THREAD

**Issue by nicksardo** [tagyoureit/nodejs-poolController#854]
### nodejs-poolController Version/commit

8.0.3

### Are you using Docker?

- [X] Yes.

### What steps will reproduce the bug?

My docker-compose file:
```
  pool-controller:
    container_name: pool-controller
    image: "msmi/nodejs-poolcontroller:8.0.3"
    restart: always
    group_add:
      - dialout
    devices:
      - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB0OHEL7-if00-port0:/dev/ttyUSB0
    ports:
      - "4200:4200"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - poolctrl:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

### What happens?

Image 7.6.1 works perfectly fine, but using anything fails immediately with the following:
```
Error: Error relocating /app/node_modules/@serialport/bindings/build/Release/bindings.node: _ZN2v82V818GlobalizeReferenceEPNS_8internal7IsolateEPm: symbol not found
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/app/node_modules/@serialport/bindings/lib/linux.js:2:36)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/node_modules/@serialport/bindings/lib/index.js:14:22)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
```

### What should have happened?

Logs show the following with 7.6.1:
```
Init state for Pool Controller
Pentair EasyTouch System Detected!
RS485 Stats:{ "bytesReceived": 1219 "success": 48, "failed": 1, "bytesSent": 456, "collisions": 0, "failureRate": 2.04% }
```

**Comment by tagyoureit** [comment]
njsPC v8 and the SerialPort module require node v16 or greater (16 or 18 recommended).  You will need to rebuild the dependencies (`npm i`).  

Others have v8.0.x running - https://github.com/tagyoureit/nodejs-poolController/issues/786.

**Comment by tagyoureit** [comment]
@emes Owns the docker image and build.

**Comment by emes** [comment]
Hey.  Sorry for the delay @nicksardo 

As I've said before.  I'd be super happy not to own this.  It really should be done via GitHub Actions or similar by the maintainers or if someone else wants to volunteer.

Yes, something definitely changed in the source after 7.6.1.  I looked through the commits and I cannot determine what change hurt docker.  If I recall, I had to make some changes to my dockerfile to get around it. 

Having said that, it is working for me.  I am running on x86_64.

/app $ node -v
v18.18.1

Here's the Dockerfile I am using:

```
FROM node:lts-alpine AS build
RUN apk add --no-cache make gcc g++ python3 linux-headers udev tzdata
WORKDIR /app
COPY package*.json ./
COPY defaultConfig.json config.json
RUN npm ci
COPY . .
RUN npm run build
RUN npm ci --omit=dev

FROM node:lts-alpine as prod
ARG SOURCE_BRANCH
ARG SOURCE_COMMIT
ENV SOURCE_BRANCH=$SOURCE_BRANCH
ENV SOURCE_COMMIT=$SOURCE_COMMIT
RUN mkdir /app && chown node:node /app
WORKDIR /app
COPY --chown=node:node --from=build /app .
USER node
ENV NODE_ENV=production
ENTRYPOINT ["node", "dist/app.js"]```

this runs using docker buildx over a buildx cluster so I can build natively for multiple architectures.

So I'm not sure how you'd be getting a node version other than v18.18.1 from the current image as `npm ci` installs whatever package.json asks.

Also probably best to pull latest rather than 8.0.3 as updates come after each tagged version and occasionally package.json version gets updated and git tags don't get pushed at the same time.

**Comment by emes** [comment]
if after pulling msmi/nodejs-poolcontroller (without the version tag) and if it's not working let me know.

also, you can try with socat...

```
  pool-controller:
    ...
    environment:
      - POOL_NET_CONNECT=true
      - POOL_NET_HOST=socat

  socat:
    command: tcp-listen:9801,fork,reuseaddr file:/dev/ttyUSB0,b9600,raw,echo=0
    container_name: socat
    restart: always
    ports:
      - "9801:9801"
    devices:
      - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB0OHEL7-if00-port0:/dev/ttyUSB0
    image: alpine/socat
```
